name: MSpleef
version: 1.0.0 Beta
api: [1.12.0]
main: TahaTheHacker\MSpleef\Main
authors: [TahaTheHacker] [kvetinac79]
Helpers: [kvetinac79] 
load: POSTWORLD
commands:
 ms:
  description: "MSpleef Main Command"
  usage: "/ms <start/stop>"
