name: MSpleef
version: 1.0.0 Beta
api: [1.12.0]
main: TahaTheHacker\MSpleef\Main
author: TahaTheHacker
Helpers: []
load: POSTWORLD
commands:
 ms:
  description: "MSpleef Main Command"
  usage: "/ms <sub-command>"
