name: MSpleef
version: 3.5 Beta
api: [1.12.0]
main: MSpleef\MSpleef
author: MCrafters
load: POSTWORLD
commands:
 ms:
  description: "MSpleef Main Command"
  usage: "/ms <start/stop>"
permissions:
 ms.command:
  description: "Allow full access to MSpleef commands"
  default: op
  children:
   ms.command.start:
    description: "Allow executing /ms start"
    default: true
   ms.command.stop:
    description: "Allow executing /ms stop"
    default: op
   ms.command.reload:
    description: "Allow executing /ms reload"
    default: op
